# Generated by Django 4.1.5 on 2023-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_rest', '0002_perevalareas_perevaladded_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
